PH-485 - Exit job when application argocd is in degraded mode (#15475)

diff --git a/.circleci/jobs/deployments/deployments.yml b/.circleci/jobs/deployments/deployments.yml
--- a/.circleci/jobs/deployments/deployments.yml
+++ b/.circleci/jobs/deployments/deployments.yml
@@ -768,6 +768,21 @@ jobs:
                       echo ${JSON_BODY_STRING}
                       curl -m 3610 -X POST ${FUNCTION_URL} -H "Authorization: bearer $(gcloud auth print-identity-token)" -H "Content-Type: application/json" -d ${JSON_BODY_STRING} || TENANT_STATUS_CODE=1
                       exit ${TENANT_STATUS_CODE}
+
+                      # Wait PH-423
+                      # # Check if hook failed
+                      # STATUS_HEALTH=$(argocd app get ${TENANT_ID} | grep Failed | awk '{print $6}') || true
+                      # if [ -n "${STATUS_HEALTH}" ]; then
+                      #   echo "Error when deploying argocd app"
+                      #   exit 1
+                      # fi
+                      # echo "argocd app sync successfull"
+
+                      echo "============================"
+                      echo "url : https://argocd-${GOOGLE_CLUSTER_REGION}.${GOOGLE_DOMAIN}"
+                      echo "user : admin"
+                      echo "password : ${ARGOCD_PASSWORD}"
+                      echo "============================"
             - run:
                   name: Persist env vars for next jobs
                   command: |
@@ -872,6 +887,13 @@ jobs:
                   argocd login --core argocd-${GOOGLE_CLUSTER_REGION}.${GOOGLE_DOMAIN} --username admin --password ${ARGOCD_PASSWORD}
                   argocd app get ${TENANT_ID} --hard-refresh --core
                   argocd app wait --sync --health --operation ${TENANT_ID} --core
+
+                  # Check if hook failed
+                  STATUS_HEALTH=$(argocd app get ${TENANT_ID} | grep Failed | awk '{print $6}') || true
+                  if [ -n "${STATUS_HEALTH}" ]; then
+                    echo "Error when deploying argocd app"
+                    exit 1
+                  fi
                   echo "argocd app sync successfull"
 
                   echo "============================"
