BH-21 Adds PR GE env (#10749)
Co-authored-by: Steven VAIDIE <steven.vaidie@gmail.com>
Co-authored-by: jean-marie leroux <jmleroux.pro@gmail.com>

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -636,6 +636,90 @@ jobs:
               command: ENV_NAME=dev INSTANCE_NAME_PREFIX=pimci-pr INSTANCE_NAME=pimci-pr-${CIRCLE_PULL_REQUEST##*/} PIM_CONTEXT=deployment make delete
               when: on_fail
 
+  prepare_pr_ge_environment:
+      environment:
+          <<: *envVarsDeployDev
+      machine:
+          image: ubuntu-2004:202010-01
+      steps:
+          - attach_workspace:
+              at: ~/
+          - set_gcloud_config_dev
+          - restore_persisted_env_vars
+          - run:
+              name: Get CE version from same branch name or master
+              command: |
+                if curl --output /dev/null --silent --head --fail https://github.com/akeneo/pim-community-dev/tree/${CIRCLE_BRANCH}; then
+                    CE_BRANCH=${CIRCLE_BRANCH}
+                else
+                    CE_BRANCH=master
+                fi
+                IMAGE_TAG=$(echo growth-$CIRCLE_SHA1 | cut -b 1-40)
+                echo "CE branch to use: $CE_BRANCH"
+                echo "Image tag: $IMAGE_TAG"
+                echo export IMAGE_TAG=$IMAGE_TAG >> $BASH_ENV
+                echo export CE_BRANCH=$CE_BRANCH >> $BASH_ENV
+          - run:
+              name: Install yq
+              command: |
+                wget https://github.com/mikefarah/yq/releases/download/2.4.0/yq_linux_386
+                sudo mv yq_linux_386 /usr/local/bin/yq
+                sudo chmod +x /usr/local/bin/yq
+          - run:
+              name: Prepare the Growth Edition
+              command: |
+                mv /home/circleci/project /home/circleci/ee_project
+                git clone --branch $CE_BRANCH git@github.com:akeneo/pim-community-dev.git /home/circleci/project
+                cd /home/circleci/project
+                /home/circleci/ee_project/growth_edition/prepare_growth_edition.sh /home/circleci/project
+          - run:
+              name: Build the Growth Edition prod image
+              command: |
+                DOCKER_BUILDKIT=1 docker build --no-cache --progress=plain --pull --target prod \
+                  --tag eu.gcr.io/akeneo-ci/pim-enterprise-dev:$IMAGE_TAG \
+                  --build-arg COMPOSER_AUTH=${COMPOSER_AUTH} .
+                docker push eu.gcr.io/akeneo-ci/pim-enterprise-dev:$IMAGE_TAG
+          - run:
+              name: Persist env vars for next jobs
+              command: |
+                  echo export IMAGE_TAG=$IMAGE_TAG >> persisted_env_vars
+                  echo export IMAGE_TAG_SHORTED=$(echo $CIRCLE_SHA1 | cut -c -7) >> persisted_env_vars
+                  echo export TYPE="grth" >> persisted_env_vars
+                  echo export PRODUCT_REFERENCE_TYPE="growth_edition_instance" >> persisted_env_vars
+                  echo export PRODUCT_REFERENCE_CODE="growth_edition_sandbox" >> persisted_env_vars
+          - persist_to_workspace:
+              root: ~/
+              paths:
+                - project
+
+  deploy_pr_ge_environment:
+      environment:
+          <<: *envVarsDeployDev
+      <<: *dockerCloudDeployer
+      steps:
+          - attach_workspace:
+              at: ~/
+          - set_gcloud_config_dev
+          - restore_persisted_env_vars
+          - run:
+              name: Check Circle CI PR
+              command: |
+                if [[ ${CIRCLE_PULL_REQUEST##*/} == "" ]]; then echo "ERROR : CIRCLE_PULL_REQUEST is empty."; exit 1;fi
+                echo "This environment will be available at https://pimci-pr-ge-${CIRCLE_PULL_REQUEST##*/}.dev.cloud.akeneo.com once deployed :) "
+          - run:
+              name: Deploy PR environment
+              command: ENV_NAME=dev INSTANCE_NAME_PREFIX=pimci-pr-ge INSTANCE_NAME=pimci-pr-ge-${CIRCLE_PULL_REQUEST##*/} ACTIVATE_MONITORING=false PIM_CONTEXT=deployment make deploy-serenity
+          - run:
+              name: Prepare infrastructure artifacts
+              command: ENV_NAME=dev INSTANCE_NAME_PREFIX=pimci-pr-ge INSTANCE_NAME=pimci-pr-ge-${CIRCLE_PULL_REQUEST##*/} PIM_CONTEXT=deployment make prepare-infrastructure-artifacts
+              when: on_fail
+          - store_artifacts:
+              path: ~/artifacts/infra
+          - run:
+              name: Remove env on kubernetes
+              command: ENV_NAME=dev INSTANCE_NAME_PREFIX=pimci-pr-ge INSTANCE_NAME=pimci-pr-ge-${CIRCLE_PULL_REQUEST##*/} PIM_CONTEXT=deployment make delete
+              when: on_fail
+
   test_upgrade_from_serenity_customer_db:
       environment:
           <<: *envVarsDeployDev
@@ -984,6 +1068,20 @@ workflows:
                 requires:
                     - deploy_pr_environment?
 
+          - deploy_pr_ge_environment?:
+                type: approval
+                filters:
+                    branches:
+                        ignore:
+                            - master
+                requires:
+                    - test_cronjobs_existence
+          - prepare_pr_ge_environment:
+                requires:
+                    - deploy_pr_ge_environment?
+          - deploy_pr_ge_environment:
+                requires:
+                    - prepare_pr_ge_environment
           - test_front_code_style:
                 requires:
                     - build_dev
