TIP-1332 add deploy in circleci config and makefile (#7260)
* TIP-1332 add deploy in circleci config and makefile

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,4 +1,19 @@
 version: 2.1
+
+aliases:
+
+  - &envVarsDeploy
+      GOOGLE_PROJECT_ID: "akecld-saas-dev"
+      GOOGLE_COMPUTE_ZONE: "europe-west3-a"
+      CLUSTER_NAME: "europe-west3-a"
+
+  - &dockerCloudDeployer
+      docker:
+        - image: eu.gcr.io/akeneo-cloud/cloud-deployer:1.5
+          auth:
+            username: _json_key  # default username when using a JSON key file to authenticate
+            password: $GCLOUD_SERVICE_KEY  # JSON service account you created, do not encode to base64
+
 jobs:
   checkout:
     docker:
@@ -256,41 +271,75 @@ jobs:
 
   build_prod:
       environment:
-        GOOGLE_PROJECT_ID: "akecld-saas-dev"
-        GOOGLE_COMPUTE_ZONE: "europe-west3-a"
-        CLUSTER_NAME: "europe-west3-a"
-      machine:
-        image: ubuntu-1604:201903-01
-      steps:
-          - attach_workspace:
-                at: ~/
-          - run:
-              name: Build prod PIM image
-              command: |
-                  echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
-                  sudo apt-get update && sudo apt-get install apt-transport-https \
-                                                              ca-certificates \
-                                                              google-cloud-sdk
-                  echo ${GCLOUD_SERVICE_KEY} | gcloud auth activate-service-account --key-file=-
-                  gcloud config set project ${GOOGLE_PROJECT_ID}
-                  gcloud config set compute/zone ${GOOGLE_COMPUTE_ZONE}
-                  echo ${GCLOUD_SERVICE_KEY} > ${HOME}/gcloud-service-key.json
-                  echo 'export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/gcloud-service-key.json"' >> $BASH_ENV
-                  gcloud auth configure-docker --quiet
-                  IMAGE_TAG=$CIRCLE_SHA1 make php-image-prod
-                  IMAGE_TAG=$CIRCLE_SHA1 make push-php-image-prod
-
-  test_prod:
+        <<: *envVarsDeploy
       machine:
           image: ubuntu-1604:201903-01
       steps:
-          -   attach_workspace:
-                  at: ~/
-          -   run:
-                  name: make test-prod
-                  command: |
-                      docker load -i pim-image-prod.tar
-                      make test-prod
+          - attach_workspace:
+                at: ~/
+          - set_gcloud_config
+          - run:
+              name: Build PROD PIM docker image
+              command: IMAGE_TAG=$CIRCLE_SHA1 make php-image-prod
+          - run:
+              name: Push PROD PIM image on docker registry
+              command: IMAGE_TAG=$CIRCLE_SHA1 make push-php-image-prod
+
+  deploy_new_environment:
+      environment:
+        <<: *envVarsDeploy
+      <<: *dockerCloudDeployer
+      steps:
+          - attach_workspace:
+                at: ~/
+          - set_gcloud_config
+          - prepare_terraform
+          - run:
+              name: Prepare helm deployment on kubernetes
+              command: make helm-prepare
+          - run:
+              name: Deploy PIM on kubernetes
+              command: IMAGE_TAG=$CIRCLE_SHA1 make deploy
+          - run:
+              name: Delete FAILED validation env
+              when: on_fail
+              shell: "/bin/bash -eo pipefail"
+              command: |
+                echo "DEPLOY FAILED - Delete CI env PFID=srnt-ci-$CIRCLE_SHA1"
+                IMAGE_TAG=$CIRCLE_SHA1 make delete
+
+  test_prod:
+      environment:
+        <<: *envVarsDeploy
+      <<: *dockerCloudDeployer
+      steps:
+          - attach_workspace:
+                at: ~/
+          - set_gcloud_config
+          - prepare_terraform
+          - run:
+              name: Deploy PIM on kubernetes
+              command: IMAGE_TAG=$CIRCLE_SHA1 make test-pim-connection
+          - run:
+              name: Delete FAILED validation env
+              when: on_fail
+              shell: "/bin/bash -eo pipefail"
+              command: |
+                echo "DEPLOY FAILED - Delete CI env PFID=srnt-ci-$CIRCLE_SHA1"
+                IMAGE_TAG=$CIRCLE_SHA1 make delete
+
+  destroy_new_environment:
+      environment:
+        <<: *envVarsDeploy
+      <<: *dockerCloudDeployer
+      steps:
+          - attach_workspace:
+                at: ~/
+          - set_gcloud_config
+          - prepare_terraform
+          - run:
+              name: Remove PIM kubernetes resources
+              command: IMAGE_TAG=$CIRCLE_SHA1 make delete
 
   release:
       machine:
@@ -405,6 +454,15 @@ workflows:
           - build_prod:
                 requires:
                     - checkout
+          - deploy_new_environment:
+                requires:
+                    - build_prod
+          - test_prod:
+                requires:
+                    - deploy_new_environment
+          - destroy_new_environment:
+                requires:
+                    -  test_prod
           - test_back_static_and_acceptance:
                 requires:
                     - build_dev
@@ -417,13 +475,38 @@ workflows:
           - back_behat_legacy:
                 requires:
                     - build_dev
-          - test_prod:
-                requires:
-                    - build_prod
           - release:
                 requires:
                     - test_back_static_and_acceptance
                     - test_front_static_acceptance_and_integration
                     - test_back_phpunit
                     - back_behat_legacy
-                    - test_prod
+                    - destroy_new_environment
+
+
+commands:
+  set_gcloud_config:
+    description: "Authenticate on GCP services and set config and key to be used by other tools that need to authenticate."
+    steps:
+      - run:
+          name: "Set Gcloud Config."
+          shell: "/bin/bash -eo pipefail"
+          command: |
+            echo ${GCLOUD_SERVICE_KEY} | gcloud auth activate-service-account --key-file=-
+            gcloud config set project ${GOOGLE_PROJECT_ID}
+            gcloud config set compute/zone ${GOOGLE_COMPUTE_ZONE}
+            echo ${GCLOUD_SERVICE_KEY} > ${HOME}/gcloud-service-key.json
+            echo 'export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/gcloud-service-key.json"' >> $BASH_ENV
+            export GOOGLE_APPLICATION_CREDENTIALS="${HOME}/gcloud-service-key.json"
+            gcloud auth configure-docker --quiet
+
+
+  prepare_terraform:
+    description: "Prepare terraform configuration."
+    steps:
+      - run:
+          name: "Prepare terraform configuration."
+          shell: "/bin/bash -eo pipefail"
+          command: |
+            IMAGE_TAG=$CIRCLE_SHA1 make create-tf-files
+            make get-kubeconfig
