BH-579 - Standardize the deploy jobs (#10979)
* fix helpdesk deploy
* fix pm deploy
* Standardize deploy

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1157,31 +1157,36 @@ jobs:
                 at: ~/
             - set_gcloud_config_preprod
             - add_ssh_keys
-            - restore_persisted_env_vars
             - run:
-                name: Get latest release
+                name: Define value for next steps
                 command: |
-                    ssh-keyscan github.com >> ~/.ssh/known_hosts
-                    git tag --list | grep -E "^v?[0-9]+$" | sort -r > /tmp/pim-tags.txt
-                    RELEASE_TO_DEPLOY=$(head -n 1 /tmp/pim-tags.txt)
-                    echo export IMAGE_TAG=${RELEASE_TO_DEPLOY} >> $BASH_ENV
-                    echo export ENV_NAME=preprod >> $BASH_ENV
-                    echo export INSTANCE_NAME=pimci-helpdesk >> $BASH_ENV
-                    echo export PIM_CONTEXT=deployment >> $BASH_ENV
-                    echo export ACTIVATE_MONITORING=true >> $BASH_ENV
+                  TYPE="srnt"
+                  ssh-keyscan github.com >> ~/.ssh/known_hosts
+                  git tag --list | grep -E "^v?[0-9]+$" | sort -r > /tmp/pim-tags.txt
+                  RELEASE_TO_DEPLOY=$(head -n 1 /tmp/pim-tags.txt)
+                  INSTANCE_NAME="pimci-helpdesk"
+                  PRODUCT_REFERENCE_TYPE="serenity_instance"
+                  PRODUCT_REFERENCE_CODE="serenity_${ENV_NAME}"
+                  PIM_CONTEXT=deployment
+                  ACTIVATE_MONITORING=true
+
+                  echo export TYPE=${TYPE} >> $BASH_ENV
+                  echo export RELEASE_TO_DEPLOY=${RELEASE_TO_DEPLOY} >> $BASH_ENV
+                  echo export INSTANCE_NAME=${INSTANCE_NAME} >> $BASH_ENV
+                  echo export PRODUCT_REFERENCE_TYPE=${PRODUCT_REFERENCE_TYPE} >> $BASH_ENV
+                  echo export PRODUCT_REFERENCE_CODE=${PRODUCT_REFERENCE_CODE} >> $BASH_ENV
+                  echo export PIM_CONTEXT=${PIM_CONTEXT} >> $BASH_ENV
+                  echo export ACTIVATE_MONITORING=${ACTIVATE_MONITORING} >> $BASH_ENV
             - run:
                 name: Generate config files and deploy
                 command: |
-                    PIM_CONTEXT=deployment make create-ci-release-files
-                    PIM_CONTEXT=deployment make change-terraform-source-version
-            - run:
-                name: Deploy
-                command: |
-                    PIM_CONTEXT=deployment UPGRADE_STEP_2=true make deploy
+                    IMAGE_TAG=${RELEASE_TO_DEPLOY} make create-ci-release-files
+                    IMAGE_TAG=${RELEASE_TO_DEPLOY} make change-terraform-source-version
+                    UPGRADE_STEP_2=true IMAGE_TAG=${RELEASE_TO_DEPLOY} make deploy
             - run:
                 name: Communicate
                 command: |
-                    PIM_CONTEXT=deployment make slack_helpdesk
+                    make slack_helpdesk
 
   deploy_pm_environment:
       environment:
@@ -1191,12 +1196,30 @@ jobs:
           - attach_workspace:
                 at: ~/
           - set_gcloud_config_preprod
-          - restore_persisted_env_vars
           - add_ssh_keys
           - run:
-                name: Latest master version for PMs
-                command: |
-                    ACTIVATE_MONITORING=true INSTANCE_NAME=pimci-pm PIM_CONTEXT=deployment UPGRADE_STEP_2=true make deploy-serenity
+              name: Define value for next steps
+              command: |
+                TYPE="srnt"
+                IMAGE_TAG=${CIRCLE_SHA1}
+                IMAGE_TAG_SHORTED=$(echo ${IMAGE_TAG} | cut -c -7)
+                INSTANCE_NAME="pimci-pm"
+                PRODUCT_REFERENCE_TYPE="serenity_instance"
+                PRODUCT_REFERENCE_CODE="serenity_${ENV_NAME}"
+                PIM_CONTEXT=deployment
+                ACTIVATE_MONITORING=true
+
+                echo export TYPE=${TYPE} >> $BASH_ENV
+                echo export IMAGE_TAG=${IMAGE_TAG} >> $BASH_ENV
+                echo export INSTANCE_NAME=${INSTANCE_NAME} >> $BASH_ENV
+                echo export PRODUCT_REFERENCE_TYPE=${PRODUCT_REFERENCE_TYPE} >> $BASH_ENV
+                echo export PRODUCT_REFERENCE_CODE=${PRODUCT_REFERENCE_CODE} >> $BASH_ENV
+                echo export PIM_CONTEXT=${PIM_CONTEXT} >> $BASH_ENV
+                echo export ACTIVATE_MONITORING=${ACTIVATE_MONITORING} >> $BASH_ENV
+          - run:
+              name: Latest master version for PMs
+              command: |
+                UPGRADE_STEP_2=true make deploy-instance
 
   deploy_pr_srnt_environment:
       environment:
@@ -1208,22 +1231,41 @@ jobs:
           - set_gcloud_config_dev
           - restore_persisted_env_vars
           - run:
-                name: Deploy PR environment
-                command: |
-                    if [[ ${CIRCLE_PULL_REQUEST##*/} == "" ]]; then echo "ERROR : CIRCLE_PULL_REQUEST is empty."; exit 1;fi
-                    echo "This environment will be available at https://pimci-pr-${CIRCLE_PULL_REQUEST##*/}.dev.cloud.akeneo.com once deployed :) "
+              name: Define value for next steps
+              command: |
+                INSTANCE_NAME_PREFIX=pimci-pr
+                INSTANCE_NAME=${INSTANCE_NAME_PREFIX}-${CIRCLE_PULL_REQUEST##*/}
+                PIM_CONTEXT=deployment
+                ACTIVATE_MONITORING=true
+
+                echo export IMAGE_TAG=${IMAGE_TAG} >> $BASH_ENV
+                echo export INSTANCE_NAME_PREFIX=${INSTANCE_NAME_PREFIX} >> $BASH_ENV
+                echo export INSTANCE_NAME=${INSTANCE_NAME} >> $BASH_ENV
+                echo export PRODUCT_REFERENCE_TYPE=${PRODUCT_REFERENCE_TYPE} >> $BASH_ENV
+                echo export PRODUCT_REFERENCE_CODE=${PRODUCT_REFERENCE_CODE} >> $BASH_ENV
+                echo export PIM_CONTEXT=${PIM_CONTEXT} >> $BASH_ENV
+                echo export ACTIVATE_MONITORING=${ACTIVATE_MONITORING} >> $BASH_ENV
+
+                echo "Instance name prefix: ${INSTANCE_NAME_PREFIX}"
+                echo "Instance name: ${INSTANCE_NAME}"
+                echo "Image tag: ${IMAGE_TAG}"
           - run:
-                name: Deploy PR environment
-                command: ENV_NAME=dev INSTANCE_NAME_PREFIX=pimci-pr INSTANCE_NAME=pimci-pr-${CIRCLE_PULL_REQUEST##*/} PIM_CONTEXT=deployment make deploy-serenity
+              name: Check Circle CI PR
+              command: |
+                if [[ ${CIRCLE_PULL_REQUEST##*/} == "" ]]; then echo "ERROR : CIRCLE_PULL_REQUEST is empty."; exit 1;fi
+                echo "This environment will be available at https://${INSTANCE_NAME}.dev.cloud.akeneo.com once deployed :)"
+          - run:
+              name: Deploy PR environment
+              command: make deploy-instance
           - run:
               name: Prepare infrastructure artifacts
-              command: ENV_NAME=dev INSTANCE_NAME_PREFIX=pimci-pr INSTANCE_NAME=pimci-pr-${CIRCLE_PULL_REQUEST##*/} PIM_CONTEXT=deployment make prepare-infrastructure-artifacts
+              command: make prepare-infrastructure-artifacts
               when: on_fail
           - store_artifacts:
               path: ~/artifacts/infra
           - run:
               name: Remove env on kubernetes
-              command: ENV_NAME=dev INSTANCE_NAME_PREFIX=pimci-pr INSTANCE_NAME=pimci-pr-${CIRCLE_PULL_REQUEST##*/} PIM_CONTEXT=deployment make delete
+              command: make delete
               when: on_fail
 
   deploy_pr_grth_environment:
@@ -1236,22 +1278,41 @@ jobs:
           - set_gcloud_config_dev
           - restore_persisted_env_vars
           - run:
+              name: Define value for next steps
+              command: |
+                INSTANCE_NAME_PREFIX=pimci-pr-ge
+                INSTANCE_NAME=${INSTANCE_NAME_PREFIX}-${CIRCLE_PULL_REQUEST##*/}
+                PIM_CONTEXT=deployment
+                ACTIVATE_MONITORING=true
+
+                echo export IMAGE_TAG=${IMAGE_TAG} >> $BASH_ENV
+                echo export INSTANCE_NAME_PREFIX=${INSTANCE_NAME_PREFIX} >> $BASH_ENV
+                echo export INSTANCE_NAME=${INSTANCE_NAME} >> $BASH_ENV
+                echo export PRODUCT_REFERENCE_TYPE=${PRODUCT_REFERENCE_TYPE} >> $BASH_ENV
+                echo export PRODUCT_REFERENCE_CODE=${PRODUCT_REFERENCE_CODE} >> $BASH_ENV
+                echo export PIM_CONTEXT=${PIM_CONTEXT} >> $BASH_ENV
+                echo export ACTIVATE_MONITORING=${ACTIVATE_MONITORING} >> $BASH_ENV
+
+                echo "Instance name prefix: ${INSTANCE_NAME_PREFIX}"
+                echo "Instance name: ${INSTANCE_NAME}"
+                echo "Image tag: ${IMAGE_TAG}"
+          - run:
               name: Check Circle CI PR
               command: |
                 if [[ ${CIRCLE_PULL_REQUEST##*/} == "" ]]; then echo "ERROR : CIRCLE_PULL_REQUEST is empty."; exit 1;fi
-                echo "This environment will be available at https://pimci-pr-ge-${CIRCLE_PULL_REQUEST##*/}.dev.cloud.akeneo.com once deployed :) "
+                echo "This environment will be available at https://${INSTANCE_NAME}.dev.cloud.akeneo.com once deployed :)"
           - run:
               name: Deploy PR environment
-              command: ENV_NAME=dev INSTANCE_NAME_PREFIX=pimci-pr-ge INSTANCE_NAME=pimci-pr-ge-${CIRCLE_PULL_REQUEST##*/} PIM_CONTEXT=deployment make deploy-serenity
+              command: make deploy-instance
           - run:
               name: Prepare infrastructure artifacts
-              command: ENV_NAME=dev INSTANCE_NAME_PREFIX=pimci-pr-ge INSTANCE_NAME=pimci-pr-ge-${CIRCLE_PULL_REQUEST##*/} PIM_CONTEXT=deployment make prepare-infrastructure-artifacts
-              when: always
+              command: make prepare-infrastructure-artifacts
+              when: on_fail
           - store_artifacts:
               path: ~/artifacts/infra
           - run:
               name: Remove env on kubernetes
-              command: ENV_NAME=dev INSTANCE_NAME_PREFIX=pimci-pr-ge INSTANCE_NAME=pimci-pr-ge-${CIRCLE_PULL_REQUEST##*/} PIM_CONTEXT=deployment make delete
+              command: make delete
               when: on_fail
 
   ##################
@@ -1322,10 +1383,6 @@ workflows:
                     - test_cronjobs_existence_srnt
           - deploy_pr_srnt_environment?:
                 type: approval
-                filters:
-                    branches:
-                        ignore:
-                            - master
                 requires:
                     - test_cronjobs_existence_srnt
           - deploy_pr_srnt_environment:
@@ -1333,10 +1390,6 @@ workflows:
                     - deploy_pr_srnt_environment?
           - deploy_pr_grth_environment?:
                 type: approval
-                filters:
-                    branches:
-                        ignore:
-                            - master
                 requires:
                     - test_cronjobs_existence_grth
           - build_grth:
